### ISSUE TITLE
希望增加-点击player播放进度条的事件监听

### ISSUE THREAD

**Issue by qwe1177** [oct16/TimeCat#118]
- [ ] I have searched the [issues](https://github.com/oct16/TimeCat/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
点击的时候显示当前进度条节点的时间

### What does the proposed API look like?
类似player.on('process', (...args) => {
    // event here
}))

**Comment by oct16** [comment]
可以使用 player.on('jump', callback)
后面会完善文档

**Comment by qwe1177** [comment]
已解决
