### ISSUE TITLE
关于带权限系统的录制

### ISSUE THREAD

**Issue by yoonper** [oct16/TimeCat#17]
TimeCat 需要加载目标页 + 记录动作来进行回放
我的需求是录制带权限的页面，回放时加载目标页用户可能无权访问，这种情况能支持吗？谢谢！

**Comment by cbbfcd** [comment]
这部分工作不应该是 TimeCat 完成的吧？

**Comment by 4d3e9v9** [comment]
这种场景比较常见，如果不缓存页面，似乎很难实现

**Comment by yoonper** [comment]
这种场景比较常见

**Comment by oct16** [comment]
TimeCat录制的的是HTML的呈现，意味着不会调用后台的接口，和权限无关，所见即所得，但是加载的资源不能有权限限制，不知道是否回答了题主的问题

**Comment by yoonper** [comment]
明白了，TimeCat 还有记录 Dom 节点，谢谢！
