### ISSUE TITLE
在一些页面的滑动滚动的过程播放不出来

### ISSUE THREAD

**Issue by qianlushahun** [oct16/TimeCat#42]
在一些浏览器中（安卓的微信里），长页面的滑动过程播放不出来。
猜测是高度获取的问题。
下面是摘取的录制的数据。
{"data":{"top":0,"left":0},"time":"1598499278169.9","type":"SCROLL"}
{"data":{"top":0,"left":0},"time":"1598499278672","type":"SCROLL"}
{"data":{"top":0,"left":0},"time":"1598499279175.4","type":"SCROLL"}
{"data":{"top":0,"left":0},"time":"1598499279675.4","type":"SCROLL"}

**Comment by oct16** [comment]
已定位，下个版本修复，谢谢报告

**Comment by qianlushahun** [comment]
> 已定位，下个版本修复，谢谢报告

您好，长页面内的一些组件的高度获取也有一些问题。例如弹框，日期选择器等。

**Comment by qianlushahun** [comment]
问题已经解决，谢谢
