### ISSUE TITLE
./timecat .global.js

### ISSUE THREAD

**Issue by randy-johnson** [oct16/TimeCat#45]
I notice this is referenced in the examples but I do not see the page in the repo.

` ./timecat .global.js `

**Comment by oct16** [comment]
You can get this file from the CDN, see: [jsDelivr](https://cdn.jsdelivr.net/npm/timecatjs), or in the dev mode, run command: ``yarn dev``

**Comment by randy-johnson** [comment]
That makes sense.  I wasn't used to seeing the library file with global in the name.  Thanks
