### ISSUE TITLE
有一些想法

### ISSUE THREAD

**Issue by dyxang** [oct16/TimeCat#5]
只是个人的一点想法。
能不能做成浏览器插件，支持录制数据的导出和导入？
因为我发现可以有这样一种使用场景，当一个网络小白需要一些基于网页的帮助时，用文字描述可能有点困难，录视频又得一步步照着做，还不如在这边直接录好动作，让ta导入插件，自动完成操作。

**Comment by oct16** [comment]
想法挺好的，你说的可能比较像网页游戏里的“自动挂机”或“自动任务”模式，不过不太适用目前的产品形态

**Comment by dyxang** [comment]
> 想法挺好的，你说的可能比较像网页游戏里的“自动挂机”或“自动任务”模式，不过不太适用目前的产品形态

仅仅是讨论，其实我的意思总结出来就是：
不手动在网页插入播放/录制；录制数据能导入导出
说个详细场景：
比如要教一个小白(完全不会用Github)如何使用Github 创建自己的博客，我只需要在这一头用浏览器录制好动作，然后导出发给他，他导入浏览器后去做别的事情(比如泡一杯茶)，回来时就已经创建好了。

**Comment by oct16** [comment]
看起来有点像RPA

**Comment by dyxang** [comment]
> 看起来有点像RPA

感觉自己已经说出来了，浏览器脚本录制……就是不需要在网页插入代码，用插件录制后，再播放。
