### ISSUE TITLE
关于 Timecat 抄袭的嫌疑

### ISSUE THREAD

**Issue by MagicCube** [oct16/TimeCat#56]
Timecat 的作者你好，我是阿里巴巴 XReplay 的负责人。从你的文档看，无论是技术细节、文案、创意都有抄袭的嫌疑。我看到你的 Github 说感谢 XReplay 启发，连文案都类似于我唯一在阿里外的 D2 大会公开演讲过的 PPT ，我猜你就在台下吧。我们在2018年申请了专利，包括 virtual dom 和分块压缩上传。我在大会上也多次强调我们申请了专利保护。

https://github.com/d2forum/14th/blob/master/PPT/「D2之夜」7%20x%2024%20小时录屏背后的黑科技--亨睿.pdf大家可以打开我的 PPT 斟酌一下，公开时间点是9个月前，也正是那个时间点之后，你的项目正式开始启动。

我说的抄袭并不是指代码级，而是架构、创意，就像我不会说 rrweb 和我们的架构相似。

**Comment by fangbinwei** [comment]
昨天阿里的布澜分享了`浏览器端录制技术的探索和实践`, 和XReplay是同一个项目么

**Comment by MagicCube** [comment]
@fangbinwei 请问有链接吗？我不认识布澜

**Comment by fangbinwei** [comment]
@MagicCube https://github.com/Bin-FE/binfe-salon-ppt/tree/master/2th

**Comment by oct16** [comment]
TimeCat 是本人基于兴趣爱好所开发的个人开源项目，本着学习与成长的目的，所有代码也都在 Github 上公开，没有做任何商业用途，也没有到媒体上推广。

录屏技术实际上在很久之前就已经在社区上存在，在我开发之前也确实调研了大量的在社区上所存在的文章，您所列举的PPT也是在网上的公开资料，这在网络上都是可以搜索到到的，我在平时研究前端技术的时候，也确实得到了一些启发，不过事先我并不知道您所声明的任何专利，同时我在文章的后面注明了您的项目，对您在社区上所做的分享表达感谢，不过您在未和我事先有过任何交流的情况下，就认定我对您侵权，并在网上公开给我扣上了抄袭的帽子，实际上已经影响到了我个人的平静生活。

对于您的看法，我想有几点需要进行回应：

1. 您在互联网上公开发表的一些文章，我在未主动与您沟通的情况下进行了引用，若您觉得不合适，我之后会撤下相应的内容。

2. 对于录屏技术，这在很早的时间节点上，就是业内公开的方法了，虽然相对比较小众，但是国内国外的技术社区都有各自技术上的实现。包括您所说的“virtual-dom”，和“分块压缩上传”，据我所知这早已经是社区上非常普遍的技术了，我没有看过您的任何代码，在此之前也未知您的相关专利，并不知道这样的操作也可能侵犯到您的权利。录屏技术实际上在行业内有大量的商业化应用，包括国内国外的大量产品都有涉及，同时国内各个大厂的内部技术部门都有类似的具体实现，我也不是这个领域的唯一开发者

3. 本人作为一个基层码农，对于互联网技术长期都抱着 “取之于社区，回馈于社区” 的初衷，一直虚心学习，热衷分享，未曾想到有一天有可能会惹上阿里巴巴。身为技术人员，当然希望能够捍卫技术的严肃性，但是在事情尚无定论之前，希望您不要到社区散布言论，希望能保持沟通，合理解决。

**Comment by CharlesMoone** [comment]
意思是，这种也算issue了？

**Comment by CharlesMoone** [comment]
贴点有用的证据吧，专利链接，和你们的idea和思想的对比。光这样一句抄袭创意也不大够吧。rrweb也实现过。

**Comment by nostarsnow** [comment]
> 贴点有用的证据吧，专利链接，和你们的idea和思想的对比。光这样一句抄袭创意也不大够吧。rrweb也实现过。

+1。我用的是`rrweb`。本来还想试用一下`timecat`看看有什么异同。这位`XReplay`作者的一席话倒是让我陷入了深思。难道只有用国外的方案才不用操心项目遇到这种情况吗？万一用国内的涉及到"侵权"停更了呢。。。

**Comment by MagicCube** [comment]
请注意我没有说代码抄袭，而是特别指出技术细节、甚至你的文案都涉嫌抄袭（这一点不恶劣吗？！）。XReplay  不是开源软件，是商业软件，这有着本质的区别。

另外，专利号 CN111488259A，可以自行搜索。

**Comment by MagicCube** [comment]
> > 贴点有用的证据吧，专利链接，和你们的idea和思想的对比。光这样一句抄袭创意也不大够吧。rrweb也实现过。
> 
> +1。我用的是`rrweb`。本来还想试用一下`timecat`看看有什么异同。这位`XReplay`作者的一席话倒是让我陷入了深思。难道只有用国外的方案才不用操心项目遇到这种情况吗？万一用国内的涉及到"侵权"停更了呢。。。

你当然可以用 rrweb，因为它是开源软件，同样也可以借鉴他公开的技术思路。

**Comment by MagicCube** [comment]
> https://github.com/Bin-FE/binfe-salon-ppt/tree/master/2th

抱歉，这不是 XReplay。

**Comment by MagicCube** [comment]
> 贴点有用的证据吧，专利链接，和你们的idea和思想的对比。光这样一句抄袭创意也不大够吧。rrweb也实现过。

证据在我的 PPT 中都有。公开的信息不代表就可以随意借鉴。否则没有人敢在技术大会上公开技术细节了 。请务必明白开源软件、社区共建和商业软件的区别。

**Comment by MagicCube** [comment]
> TimeCat 是本人基于兴趣爱好所开发的个人开源项目，本着学习与成长的目的，所有代码也都在 Github 上公开，没有做任何商业用途，也没有到媒体上推广。
> 
> 录屏技术实际上在很久之前就已经在社区上存在，在我开发之前也确实调研了大量的在社区上所存在的文章，您所列举的PPT也是在网上的公开资料，这在网络上都是可以搜索到到的，我在平时研究前端技术的时候，也确实得到了一些启发，不过事先我并不知道您所声明的任何专利，同时我在文章的后面注明了您的项目，对您在社区上所做的分享表达感谢，不过您在未和我事先有过任何交流的情况下，就认定我对您侵权，并在网上公开给我扣上了抄袭的帽子，实际上已经影响到了我个人的平静生活。
> 
> 对于您的看法，我想有几点需要进行回应：
> 
> 1. 您在互联网上公开发表的一些文章，我在未主动与您沟通的情况下进行了引用，若您觉得不合适，我之后会撤下相应的内容。
> 2. 对于录屏技术，这在很早的时间节点上，就是业内公开的方法了，虽然相对比较小众，但是国内国外的技术社区都有各自技术上的实现。包括您所说的“virtual-dom”，和“分块压缩上传”，据我所知这早已经是社区上非常普遍的技术了，我没有看过您的任何代码，在此之前也未知您的相关专利，并不知道这样的操作也可能侵犯到您的权利。录屏技术实际上在行业内有大量的商业化应用，包括国内国外的大量产品都有涉及，同时国内各个大厂的内部技术部门都有类似的具体实现，我也不是这个领域的唯一开发者
> 3. 本人作为一个基层码农，对于互联网技术长期都抱着 “取之于社区，回馈于社区” 的初衷，一直虚心学习，热衷分享，未曾想到有一天有可能会惹上阿里巴巴。身为技术人员，当然希望能够捍卫技术的严肃性，但是在事情尚无定论之前，希望您不要到社区散布言论，希望能保持沟通，合理解决。

请注意我始终用的都是“抄袭嫌疑”。

**Comment by oct16** [comment]
> > 贴点有用的证据吧，专利链接，和你们的idea和思想的对比。光这样一句抄袭创意也不大够吧。rrweb也实现过。
> 
> 证据在我的 PPT 中都有。公开的信息不代表就可以随意借鉴。否则没有人敢在技术大会上公开技术细节了 。请务必明白开源软件、社区共建和商业软件的区别。

我再次声明，您的PPT是互联网的公开的资料，里面没有任何地方注明涉及了任何专利，而且为了避免纠纷，在您联系我之后我当天就进行了修改

我的编写的只是一篇技术文章，列举我了我的一些调研，目的是简单的介绍录屏器的基本原理，和社区中各种技术文章无本质区别。我从来没有说过这些是我发明的技术，而是一直强调来源于社区，文章里面包含了大量的引用和出处，并且也多次注明了您的项目 XReplay ，我没有任何必要抄去袭您所谓的 Idea。

另外我一直以为阿里巴巴举办的前端技术论坛和其他论坛一样，是一个技术交流，借鉴思路，相互成长的地方，例如就像这个文章介绍这样： [如何优雅地参加技术分享会？](https://zhuanlan.zhihu.com/p/22322885) 我天真的以为讨论的技术话题和公布的PPT是可以用来学习和参考的，请原谅我年轻无知

**Comment by oct16** [comment]
> 请注意我没有说代码抄袭，而是特别指出技术细节、甚至你的文案都涉嫌抄袭（这一点不恶劣吗？！），我想 oct16 更明白我说的创意抄袭嫌疑的是哪些部分。
> 
> XReplay 不是开源软件，是商业软件，这有着本质的区别。
> 
> 专利以及 D2 公开的演讲都是属于技术公开，不能说我将家属在线上线下公开，第三方就可以模仿，否则这就失去了知识产权保护的目的。
> 
> 另外，专利号 CN111488259A，可以自行搜索。http://www.ipfeibiao.com/patent/view/2019100871664.html

1. 我的文章里面包含了大量的引用和出处，并且也多次注明了您的项目，您这样扣帽子是否妥当 
2. 您的专利申请于2019年，到目前为止仍然是处于申请中状态，没有获得审批通过
3. 您的项目启动时间明显晚于录屏技术在社区中出现的时间，例如国外的 LogRocket 是2016年就发布了

**Comment by MagicCube** [comment]
> > 请注意我没有说代码抄袭，而是特别指出技术细节、甚至你的文案都涉嫌抄袭（这一点不恶劣吗？！），我想 oct16 更明白我说的创意抄袭嫌疑的是哪些部分。
> > XReplay 不是开源软件，是商业软件，这有着本质的区别。
> > 专利以及 D2 公开的演讲都是属于技术公开，不能说我将家属在线上线下公开，第三方就可以模仿，否则这就失去了知识产权保护的目的。
> > 另外，专利号 CN111488259A，可以自行搜索。http://www.ipfeibiao.com/patent/view/2019100871664.html
> 
> 1. 我的文章里面包含了大量的引用和出处，并且也多次注明了您的项目，您这样扣帽子是否妥当
> 2. 您的专利申请于2019年，到目前为止仍然是处于申请中状态，没有获得审批通过
> 3. 您的项目启动时间明显晚于录屏技术在社区中出现的时间，例如国外的 LogRocket 是2016年就发布了

我们从没有去借鉴第三方的任何思想，所有技术实现都是原创，这也是为什么我们敢公开出来演讲和申请专利。这是我们作为技术人的追求。最后，结贴前再次强调 XReplay 不是社区软件，我在 D2 的分享不是社区分享，分享时你应该在场，应该知道我多次强调了专利。

**Comment by nostarsnow** [comment]
> > > 请注意我没有说代码抄袭，而是特别指出技术细节、甚至你的文案都涉嫌抄袭（这一点不恶劣吗？！），我想 oct16 更明白我说的创意抄袭嫌疑的是哪些部分。
> > > XReplay 不是开源软件，是商业软件，这有着本质的区别。
> > > 专利以及 D2 公开的演讲都是属于技术公开，不能说我将家属在线上线下公开，第三方就可以模仿，否则这就失去了知识产权保护的目的。
> > > 另外，专利号 CN111488259A，可以自行搜索。http://www.ipfeibiao.com/patent/view/2019100871664.html
> > 
> > 
> > 
> > 1. 我的文章里面包含了大量的引用和出处，并且也多次注明了您的项目，您这样扣帽子是否妥当
> > 2. 您的专利申请于2019年，到目前为止仍然是处于申请中状态，没有获得审批通过
> > 3. 您的项目启动时间明显晚于录屏技术在社区中出现的时间，例如国外的 LogRocket 是2016年就发布了
> 
> 我们从没有去借鉴第三方的任何思想，所有技术实现都是原创，这也是为什么我们敢公开出来演讲和申请专利。这是我们作为技术人的追求。最后，结贴前再次强调 XReplay 不是社区软件，我在 D2 的分享不是社区分享，分享时你应该在场，应该知道我多次强调了专利。

厉害了。d(ﾟ∀ﾟd)！

**Comment by hqqshe** [comment]
吃相
